### ISSUE TITLE
[console] - corrigir link para o IRC

### ISSUE THREAD

**Issue by spinolacastro** [getupcloud/origin-server#17]
![captura de tela 2015-06-29 as 08 37 20](https://cloud.githubusercontent.com/assets/1382710/8407144/24f2d25e-1e3a-11e5-91de-e36450bc371f.png)

**Comment by caruccio** [comment]
Configuração em /etc/openshift/console.conf

IRC_WEB_URL=http://webchat.freenode.net/?randomnick=1&channels=getupcloud&uio=d4

**Comment by spinolacastro** [comment]
O nome esta errado, ICR
